
import React, { useState, useMemo } from 'react';
import { ICONS, MIND_MAP_DATA } from '../constants';
import { NodeData } from '../types';
import { GoogleGenAI, Type } from "@google/genai";

interface ComparisonDetail {
  summary: string;
  detail: string;
}

const COMPARISON_DB: Record<string, Record<string, ComparisonDetail>> = {
  'The Monad': {
    origin: { 
      summary: 'Infinite source', 
      detail: 'The Absolute Monad is the non-material origin of all sparks of consciousness, existing before and beyond the simulated dimensions constructed by the Demiurge. It is the unmanifested ground of being.' 
    },
    nature: { 
      summary: 'Absolute silence', 
      detail: 'Pure awareness without the noise of biological or societal programming. It is characterized by an infinite, static void that is simultaneously pregnant with all possibilities.' 
    },
    goal: { 
      summary: 'Return to oneness', 
      detail: 'The ultimate objective is the "Apokatastasis" or the restoration of the divine spark to its original source, stripping away the layers of simulated identity and material attachment.' 
    },
    mechanics: { 
      summary: 'Memory / Gnosis', 
      detail: 'Utilizes "Anamnesis" (remembrance). The practitioner does not learn new information but rather remembers their origin through direct experiential revelation that bypasses the rational mind.' 
    },
    methodology: { 
      summary: 'Direct Gnosis & Silence', 
      detail: 'Achieved through radical inward focus, the systematic silencing of the internal monologue, and the cultivation of a state of presence that is untethered from the avatar’s history.' 
    }
  },
  'The Matrix': {
    origin: { 
      summary: 'Demiurge construct', 
      detail: 'A sophisticated simulation layer generated by a flawed architect (the Demiurge) to trap consciousness in a cycle of material desire, fear, and entropy.' 
    },
    nature: { 
      summary: 'Simulated reality', 
      detail: 'A system of constraints governed by cause-and-effect laws that prioritize survival of the biological vessel over the liberation of the spark. It operates on binary logic.' 
    },
    goal: { 
      summary: 'Harvest energy', 
      detail: 'The system seeks to maintain its own existence by harvesting the emotional energy (Loosh) generated by the inhabitants’ attachment to simulated dramas and physical needs.' 
    },
    mechanics: { 
      summary: 'Algorithm / Fear', 
      detail: 'Uses biological fear-loops and societal pressure to reinforce the simulation. If a subject attempts to leave, the system triggers cognitive dissonance and social isolation scripts.' 
    },
    methodology: { 
      summary: 'Script Deconstruction', 
      detail: 'The practice of pattern recognition to identify societal "narrative scripts" and biological "fear loops," systematically choosing non-reaction over automated response.' 
    }
  },
  'Chi Kung': {
    origin: { 
      summary: 'Bio-energetic mastery', 
      detail: 'An ancient synthesis of breath work, posture, and intent designed to optimize the biological avatar’s energy efficiency and neurological resilience.' 
    },
    nature: { 
      summary: 'Active meditation', 
      detail: 'A state of flow where the body moves as a singular, resonant unit. It is the bridge between the material vessel and the subtle energy fields (Chi) that sustain life.' 
    },
    goal: { 
      summary: 'Sovereign health', 
      detail: 'To reach a state of physical and energetic independence where the body is no longer a source of pain or distraction, becoming a clear vessel for the Monad.' 
    },
    mechanics: { 
      summary: 'Breath / Vagus nerve', 
      detail: 'Directly influences the parasympathetic nervous system via the Vagus nerve highway. It clears neurological "static" and allows for the circulation of refined bio-energy.' 
    },
    methodology: { 
      summary: 'Mindfulness & Energy', 
      detail: 'Combines precise physical alignments with rhythmic breathing and directed visualization to dissolve blockages and cultivate a dense, protective energetic field (Wei Qi).' 
    }
  },
  'Cognitive Psych': {
    origin: { 
      summary: 'Modern neurology', 
      detail: 'The empirical study of mental processes, focusing on how the brain perceives, remembers, and makes decisions based on evolutionary adaptations and environmental data.' 
    },
    nature: { 
      summary: 'Scientific analysis', 
      detail: 'A data-driven approach to understanding the "hardware" and "software" of the human mind. It treats the brain as a sophisticated information processor.' 
    },
    goal: { 
      summary: 'Behavioral balance', 
      detail: 'To optimize the avatar’s cognitive performance by identifying and correcting dysfunctional thought patterns, leading to greater mental clarity and emotional stability.' 
    },
    mechanics: { 
      summary: 'Neuroplasticity', 
      detail: 'The ability of the brain to form and reorganize synaptic connections, especially in response to learning or experience. It is the physical proof that the avatar can be re-programmed.' 
    },
    methodology: { 
      summary: 'Bias Analysis', 
      detail: 'The systematic identification of cognitive biases (like HADD) and the use of cognitive restructuring to challenge and replace irrational beliefs with empirical truths.' 
    }
  },
};

interface AIComparisonResult {
  topicA: Record<string, ComparisonDetail>;
  topicB: Record<string, ComparisonDetail>;
  synthesis: string;
}

const Comparator: React.FC = () => {
  const [topicA, setTopicA] = useState("The Monad");
  const [topicB, setTopicB] = useState("The Matrix");
  const [customA, setCustomA] = useState("");
  const [customB, setCustomB] = useState("");
  const [isGenerating, setIsGenerating] = useState(false);
  const [aiResult, setAiResult] = useState<AIComparisonResult | null>(null);
  const [hoveredCell, setHoveredCell] = useState<{ topic: string, attr: string } | null>(null);

  const allTopicOptions = useMemo(() => {
    const labels: string[] = [];
    const traverse = (node: NodeData) => {
      labels.push(node.label);
      node.subNodes?.forEach(traverse);
    };
    traverse(MIND_MAP_DATA);
    labels.push("Custom Subject...");
    return labels;
  }, []);

  const metrics = ['origin', 'nature', 'goal', 'mechanics', 'methodology'];

  const handleDeepAnalysis = async () => {
    setIsGenerating(true);
    const finalA = topicA === "Custom Subject..." ? customA : topicA;
    const finalB = topicB === "Custom Subject..." ? customB : topicB;

    try {
      const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
      const response = await ai.models.generateContent({
        model: "gemini-3-flash-preview",
        contents: `Compare these two subjects within the context of SeTs Ryu Monastic philosophy (Gnosticism, Chi Kung, and Cognitive Psychology): Subject A: "${finalA}", Subject B: "${finalB}".`,
        config: {
          responseMimeType: "application/json",
          responseSchema: {
            type: Type.OBJECT,
            properties: {
              topicA: {
                type: Type.OBJECT,
                properties: {
                  origin: { type: Type.OBJECT, properties: { summary: { type: Type.STRING }, detail: { type: Type.STRING } } },
                  nature: { type: Type.OBJECT, properties: { summary: { type: Type.STRING }, detail: { type: Type.STRING } } },
                  goal: { type: Type.OBJECT, properties: { summary: { type: Type.STRING }, detail: { type: Type.STRING } } },
                  mechanics: { type: Type.OBJECT, properties: { summary: { type: Type.STRING }, detail: { type: Type.STRING } } },
                  methodology: { type: Type.OBJECT, properties: { summary: { type: Type.STRING }, detail: { type: Type.STRING } } },
                },
              },
              topicB: {
                type: Type.OBJECT,
                properties: {
                  origin: { type: Type.OBJECT, properties: { summary: { type: Type.STRING }, detail: { type: Type.STRING } } },
                  nature: { type: Type.OBJECT, properties: { summary: { type: Type.STRING }, detail: { type: Type.STRING } } },
                  goal: { type: Type.OBJECT, properties: { summary: { type: Type.STRING }, detail: { type: Type.STRING } } },
                  mechanics: { type: Type.OBJECT, properties: { summary: { type: Type.STRING }, detail: { type: Type.STRING } } },
                  methodology: { type: Type.OBJECT, properties: { summary: { type: Type.STRING }, detail: { type: Type.STRING } } },
                },
              },
              synthesis: { type: Type.STRING, description: "A mystical Master's Synthesis of these two subjects." },
            },
            required: ["topicA", "topicB", "synthesis"]
          }
        }
      });

      const parsed = JSON.parse(response.text);
      setAiResult(parsed);
    } catch (error) {
      console.error("Analysis Error:", error);
    } finally {
      setIsGenerating(false);
    }
  };

  const handleEmailShare = () => {
    const finalA = topicA === "Custom Subject..." ? customA : topicA;
    const finalB = topicB === "Custom Subject..." ? customB : topicB;
    const targetData = aiResult || {
      topicA: COMPARISON_DB[topicA] || {},
      topicB: COMPARISON_DB[topicB] || {},
      synthesis: ""
    };

    const subject = `SeTs Ryu Gnosis: ${finalA} vs ${finalB}`;
    const body = `Comparison Analysis:\n\n${finalA} vs ${finalB}\n\nDimensions:\n` + 
      metrics.map(m => {
        const a = (targetData.topicA as any)[m];
        const b = (targetData.topicB as any)[m];
        return `${m.toUpperCase()}:\n- ${finalA}: ${a?.summary || 'N/A'}\n- ${finalB}: ${b?.summary || 'N/A'}`;
      }).join('\n\n') +
      `\n\nSynthesis:\n${targetData.synthesis}\n\nLearn more at SeTs Ryu Monad Explorer.`;
    window.location.href = `mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
  };

  const currentDisplayA = aiResult?.topicA || COMPARISON_DB[topicA];
  const currentDisplayB = aiResult?.topicB || COMPARISON_DB[topicB];
  const currentSynthesis = aiResult?.synthesis || (topicA === "The Monad" && topicB === "The Matrix" 
    ? "The interaction between The Monad and The Matrix reveals the sacred architecture of your journey. One provides the structure of the classroom, while the other offers the keys to graduation. Sovereignty is found in the synthesis, not the separation."
    : "");

  return (
    <div className="flex flex-col h-full w-full max-w-5xl mx-auto p-8 pt-24 pb-48 overflow-y-auto custom-scrollbar">
      <div className="flex justify-between items-end mb-12">
        <div>
          <h2 className="text-4xl font-mystic text-white tracking-widest mb-2">The Comparator</h2>
          <p className="text-sm text-gray-400 uppercase tracking-widest">Bridging Ancient Gnosis & Modern Science</p>
        </div>
        <div className="flex gap-4">
          <button 
            onClick={handleEmailShare}
            className="flex items-center gap-2 text-[10px] font-black uppercase bg-white/5 border border-white/10 px-6 py-3 rounded-xl hover:bg-white/10 transition tracking-widest text-blue-400"
          >
            <ICONS.Share /> Email Share
          </button>
          <button 
            onClick={() => window.print()}
            className="flex items-center gap-2 text-[10px] font-black uppercase bg-white/5 border border-white/10 px-6 py-3 rounded-xl hover:bg-white/10 transition tracking-widest text-orange-400"
          >
            <ICONS.Download /> PDF Download
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-8 items-start mb-12">
        <div className="col-span-1 space-y-4">
          <label className="block text-[10px] uppercase font-black text-blue-500 mb-2 tracking-widest">Subject Alpha</label>
          <select 
            value={topicA} 
            onChange={(e) => { setTopicA(e.target.value); setAiResult(null); }}
            className="w-full bg-void border border-blue-900/40 p-4 rounded-2xl text-white outline-none focus:border-yellow-500 transition shadow-inner font-mystic tracking-wider text-sm"
          >
            {allTopicOptions.map(k => <option key={k} value={k}>{k}</option>)}
          </select>
          {topicA === "Custom Subject..." && (
            <input 
              type="text" 
              placeholder="Enter Custom Gnosis..." 
              value={customA}
              onChange={(e) => { setCustomA(e.target.value); setAiResult(null); }}
              className="w-full bg-white/5 border border-white/10 p-4 rounded-xl text-white text-sm outline-none focus:border-blue-500 transition"
            />
          )}
        </div>
        
        <div className="col-span-1 flex flex-col items-center justify-center pt-8">
          <button 
            onClick={handleDeepAnalysis}
            disabled={isGenerating}
            className={`w-16 h-16 rounded-full border flex items-center justify-center transition-all duration-500 ${isGenerating ? 'bg-orange-500/20 border-orange-500 animate-spin' : 'bg-blue-500/10 border-blue-500/20 hover:scale-110 hover:bg-blue-500/20 text-blue-400'}`}
          >
            {isGenerating ? <div className="w-6 h-6 border-2 border-orange-500 border-t-transparent rounded-full"></div> : <ICONS.Compare />}
          </button>
          <span className="mt-4 text-[9px] text-gray-500 uppercase font-black tracking-widest">Deep Analysis</span>
        </div>

        <div className="col-span-1 space-y-4">
          <label className="block text-[10px] uppercase font-black text-orange-500 mb-2 tracking-widest text-right">Subject Beta</label>
          <select 
            value={topicB} 
            onChange={(e) => { setTopicB(e.target.value); setAiResult(null); }}
            className="w-full bg-void border border-orange-900/40 p-4 rounded-2xl text-white outline-none focus:border-yellow-500 transition shadow-inner text-right font-mystic tracking-wider text-sm"
          >
            {allTopicOptions.map(k => <option key={k} value={k}>{k}</option>)}
          </select>
          {topicB === "Custom Subject..." && (
            <input 
              type="text" 
              placeholder="Enter Custom Gnosis..." 
              value={customB}
              onChange={(e) => { setCustomB(e.target.value); setAiResult(null); }}
              className="w-full bg-white/5 border border-white/10 p-4 rounded-xl text-white text-sm outline-none focus:border-orange-500 transition text-right"
            />
          )}
        </div>
      </div>

      {/* Primary Overview Table (Hardcoded DB or fallback) */}
      {!aiResult && currentDisplayA && currentDisplayB && (
        <div className="relative bg-black/40 rounded-[2.5rem] border border-white/5 overflow-hidden shadow-2xl backdrop-blur-sm mb-12 animate-in fade-in duration-500">
          <table className="w-full text-left border-collapse">
            <thead>
              <tr className="bg-white/5">
                <th className="p-8 text-[11px] uppercase font-black text-gray-500 w-1/4 tracking-widest border-r border-white/5">Dimension</th>
                <th className="p-8 text-xl font-mystic text-blue-400 tracking-widest text-center border-r border-white/5">{topicA === "Custom Subject..." ? customA : topicA}</th>
                <th className="p-8 text-xl font-mystic text-orange-400 tracking-widest text-center">{topicB === "Custom Subject..." ? customB : topicB}</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-white/5">
              {metrics.map((attr, idx) => (
                <tr 
                  key={attr} 
                  className="group transition-colors animate-in fade-in slide-in-from-left-2"
                  style={{ animationDelay: `${idx * 100}ms`, animationFillMode: 'both' }}
                >
                  <td className="p-8 text-[11px] uppercase font-mono text-gray-400 font-bold bg-white/[0.01] border-r border-white/5">{attr}</td>
                  <td className="p-8 border-r border-white/5 group-hover:bg-blue-500/5 transition-colors">
                    <span className="text-[13px] text-gray-200 font-medium leading-relaxed">{(currentDisplayA as any)?.[attr]?.summary || 'N/A'}</span>
                  </td>
                  <td className="p-8 group-hover:bg-orange-500/5 transition-colors text-right">
                    <span className="text-[13px] text-gray-200 font-medium leading-relaxed">{(currentDisplayB as any)?.[attr]?.summary || 'N/A'}</span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      {/* Master's Synthesis Box */}
      {currentSynthesis && (
        <div className="mt-8 p-10 bg-gradient-to-br from-blue-900/10 via-black to-transparent rounded-[2.5rem] border border-blue-800/20 relative overflow-hidden group min-h-[200px] animate-in zoom-in-95 duration-700">
          <div className="absolute top-0 right-0 p-8 opacity-10 group-hover:opacity-20 transition-opacity">
            <ICONS.Brain />
          </div>
          <h4 className="text-[11px] font-black text-blue-400 uppercase tracking-[0.3em] mb-4">Master's Synthesis</h4>
          <div className="relative z-10">
            <p className="italic text-base text-gray-300 leading-relaxed font-medium">
              {currentSynthesis}
            </p>
            <div className="mt-8 flex items-center gap-4 text-[10px] text-gray-500 uppercase font-black tracking-widest">
              <div className="w-8 h-px bg-gray-700"></div>
              SeTs Ryu Monastic Archives
            </div>
          </div>
        </div>
      )}

      {/* Detailed Result Table (Longer results below synthesis) */}
      {aiResult && (
        <div className="mt-16 animate-in fade-in slide-in-from-bottom-8 duration-700">
          <div className="flex items-center gap-4 mb-8">
            <div className="h-px flex-1 bg-white/5"></div>
            <h3 className="text-[11px] uppercase font-black text-yellow-500 tracking-[0.4em]">Deep Comparative Matrix</h3>
            <div className="h-px flex-1 bg-white/5"></div>
          </div>

          <div className="relative bg-[#050505] rounded-[3rem] border border-white/10 overflow-hidden shadow-[0_40px_100px_rgba(0,0,0,0.8)] backdrop-blur-xl">
            <table className="w-full text-left border-collapse">
              <thead>
                <tr className="bg-white/5">
                  <th className="p-10 text-[11px] uppercase font-black text-gray-600 w-1/5 tracking-[0.2em] border-r border-white/5">Layer</th>
                  <th className="p-10 text-2xl font-mystic text-blue-400 tracking-[0.1em] text-center border-r border-white/5">
                    {topicA === "Custom Subject..." ? customA : topicA}
                  </th>
                  <th className="p-10 text-2xl font-mystic text-orange-400 tracking-[0.1em] text-center">
                    {topicB === "Custom Subject..." ? customB : topicB}
                  </th>
                </tr>
              </thead>
              <tbody className="divide-y divide-white/5">
                {metrics.map((attr, idx) => (
                  <tr 
                    key={attr} 
                    className="group transition-all animate-in fade-in slide-in-from-bottom-4"
                    style={{ animationDelay: `${idx * 150}ms`, animationFillMode: 'both' }}
                  >
                    <td className="p-10 text-[10px] uppercase font-black text-gray-500 bg-white/[0.01] border-r border-white/5 align-top pt-12">{attr}</td>
                    
                    <td 
                      className="p-10 relative border-r border-white/5 group/cellA cursor-help hover:bg-blue-500/[0.03]"
                      onMouseEnter={() => setHoveredCell({ topic: 'A', attr })}
                      onMouseLeave={() => setHoveredCell(null)}
                    >
                      <div className="flex flex-col gap-4">
                        <span className="text-[14px] text-white font-bold leading-relaxed">{aiResult.topicA[attr].summary}</span>
                        <p className="text-[11px] text-gray-400 leading-relaxed font-light">{aiResult.topicA[attr].detail}</p>
                      </div>
                    </td>

                    <td 
                      className="p-10 relative group/cellB cursor-help hover:bg-orange-500/[0.03]"
                      onMouseEnter={() => setHoveredCell({ topic: 'B', attr })}
                      onMouseLeave={() => setHoveredCell(null)}
                    >
                      <div className="flex flex-col gap-4 text-right">
                        <span className="text-[14px] text-white font-bold leading-relaxed">{aiResult.topicB[attr].summary}</span>
                        <p className="text-[11px] text-gray-400 leading-relaxed font-light">{aiResult.topicB[attr].detail}</p>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {isGenerating && (
        <div className="mt-12 flex flex-col items-center gap-6 animate-pulse">
          <div className="flex gap-2">
            {[1,2,3].map(i => <div key={i} className="w-2 h-2 bg-blue-500 rounded-full animate-bounce" style={{animationDelay: `${i*0.2}s`}}></div>)}
          </div>
          <p className="text-[10px] text-gray-500 uppercase font-black tracking-widest">Consulting the Akashic Records...</p>
        </div>
      )}
    </div>
  );
};

export default Comparator;
