
import React, { useState } from 'react';
import { ICONS } from '../constants';

interface ComparisonDetail {
  summary: string;
  detail: string;
}

const COMPARISON_DB: Record<string, Record<string, ComparisonDetail>> = {
  'The Monad': {
    origin: { 
      summary: 'Infinite source', 
      detail: 'The Absolute Monad is the non-material origin of all sparks of consciousness, existing before and beyond the simulated dimensions constructed by the Demiurge. It is the unmanifested ground of being.' 
    },
    nature: { 
      summary: 'Absolute silence', 
      detail: 'Pure awareness without the noise of biological or societal programming. It is characterized by an infinite, static void that is simultaneously pregnant with all possibilities.' 
    },
    goal: { 
      summary: 'Return to oneness', 
      detail: 'The ultimate objective is the "Apokatastasis" or the restoration of the divine spark to its original source, stripping away the layers of simulated identity and material attachment.' 
    },
    mechanics: { 
      summary: 'Memory / Gnosis', 
      detail: 'Utilizes "Anamnesis" (remembrance). The practitioner does not learn new information but rather remembers their origin through direct experiential revelation that bypasses the rational mind.' 
    },
    methodology: { 
      summary: 'Direct Gnosis & Silence', 
      detail: 'Achieved through radical inward focus, the systematic silencing of the internal monologue, and the cultivation of a state of presence that is untethered from the avatar’s history.' 
    }
  },
  'The Matrix': {
    origin: { 
      summary: 'Demiurge construct', 
      detail: 'A sophisticated simulation layer generated by a flawed architect (the Demiurge) to trap consciousness in a cycle of material desire, fear, and entropy.' 
    },
    nature: { 
      summary: 'Simulated reality', 
      detail: 'A system of constraints governed by cause-and-effect laws that prioritize survival of the biological vessel over the liberation of the spark. It operates on binary logic.' 
    },
    goal: { 
      summary: 'Harvest energy', 
      detail: 'The system seeks to maintain its own existence by harvesting the emotional energy (Loosh) generated by the inhabitants’ attachment to simulated dramas and physical needs.' 
    },
    mechanics: { 
      summary: 'Algorithm / Fear', 
      detail: 'Uses biological fear-loops and societal pressure to reinforce the simulation. If a subject attempts to leave, the system triggers cognitive dissonance and social isolation scripts.' 
    },
    methodology: { 
      summary: 'Script Deconstruction', 
      detail: 'The practice of pattern recognition to identify societal "narrative scripts" and biological "fear loops," systematically choosing non-reaction over automated response.' 
    }
  },
  'Chi Kung': {
    origin: { 
      summary: 'Bio-energetic mastery', 
      detail: 'An ancient synthesis of breath work, posture, and intent designed to optimize the biological avatar’s energy efficiency and neurological resilience.' 
    },
    nature: { 
      summary: 'Active meditation', 
      detail: 'A state of flow where the body moves as a singular, resonant unit. It is the bridge between the material vessel and the subtle energy fields (Chi) that sustain life.' 
    },
    goal: { 
      summary: 'Sovereign health', 
      detail: 'To reach a state of physical and energetic independence where the body is no longer a source of pain or distraction, becoming a clear vessel for the Monad.' 
    },
    mechanics: { 
      summary: 'Breath / Vagus nerve', 
      detail: 'Directly influences the parasympathetic nervous system via the Vagus nerve highway. It clears neurological "static" and allows for the circulation of refined bio-energy.' 
    },
    methodology: { 
      summary: 'Mindfulness & Energy', 
      detail: 'Combines precise physical alignments with rhythmic breathing and directed visualization to dissolve blockages and cultivate a dense, protective energetic field (Wei Qi).' 
    }
  },
  'Cognitive Psych': {
    origin: { 
      summary: 'Modern neurology', 
      detail: 'The empirical study of mental processes, focusing on how the brain perceives, remembers, and makes decisions based on evolutionary adaptations and environmental data.' 
    },
    nature: { 
      summary: 'Scientific analysis', 
      detail: 'A data-driven approach to understanding the "hardware" and "software" of the human mind. It treats the brain as a sophisticated information processor.' 
    },
    goal: { 
      summary: 'Behavioral balance', 
      detail: 'To optimize the avatar’s cognitive performance by identifying and correcting dysfunctional thought patterns, leading to greater mental clarity and emotional stability.' 
    },
    mechanics: { 
      summary: 'Neuroplasticity', 
      detail: 'The ability of the brain to form and reorganize synaptic connections, especially in response to learning or experience. It is the physical proof that the avatar can be re-programmed.' 
    },
    methodology: { 
      summary: 'Bias Analysis', 
      detail: 'The systematic identification of cognitive biases (like HADD) and the use of cognitive restructuring to challenge and replace irrational beliefs with empirical truths.' 
    }
  },
};

const Comparator: React.FC = () => {
  const [topicA, setTopicA] = useState("The Monad");
  const [topicB, setTopicB] = useState("The Matrix");
  const [hoveredCell, setHoveredCell] = useState<{ topic: string, attr: string } | null>(null);

  const dataA = COMPARISON_DB[topicA];
  const dataB = COMPARISON_DB[topicB];

  const metrics = ['origin', 'nature', 'goal', 'mechanics', 'methodology'];

  const handleEmailShare = () => {
    const subject = `SeTs Ryu Gnosis: ${topicA} vs ${topicB}`;
    const body = `Comparison Analysis:\n\n${topicA} vs ${topicB}\n\nDimensions:\n` + 
      metrics.map(m => `${m.toUpperCase()}:\n- ${topicA}: ${dataA[m].summary}\n- ${topicB}: ${dataB[m].summary}`).join('\n\n') +
      `\n\nLearn more at SeTs Ryu Monad Explorer.`;
    window.location.href = `mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
  };

  const handleDownloadPDF = () => {
    window.print();
  };

  return (
    <div className="flex flex-col h-full w-full max-w-5xl mx-auto p-8 pt-24 pb-48 overflow-y-auto custom-scrollbar">
      <div className="flex justify-between items-end mb-12">
        <div>
          <h2 className="text-4xl font-mystic text-white tracking-widest mb-2">The Comparator</h2>
          <p className="text-sm text-gray-400 uppercase tracking-widest">Bridging Ancient Gnosis & Modern Science</p>
        </div>
        <div className="flex gap-4">
          <button 
            onClick={handleEmailShare}
            className="flex items-center gap-2 text-[10px] font-black uppercase bg-white/5 border border-white/10 px-6 py-3 rounded-xl hover:bg-white/10 transition tracking-widest text-blue-400"
          >
            <ICONS.Share /> Email Share
          </button>
          <button 
            onClick={handleDownloadPDF}
            className="flex items-center gap-2 text-[10px] font-black uppercase bg-white/5 border border-white/10 px-6 py-3 rounded-xl hover:bg-white/10 transition tracking-widest text-orange-400"
          >
            <ICONS.Download /> PDF Download
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-8 items-end mb-12">
        <div className="col-span-1">
          <label className="block text-[10px] uppercase font-black text-blue-500 mb-4 tracking-widest">Subject Alpha</label>
          <select 
            value={topicA} 
            onChange={(e) => setTopicA(e.target.value)}
            className="w-full bg-void border border-blue-900/40 p-5 rounded-2xl text-white outline-none focus:border-yellow-500 transition shadow-inner font-mystic tracking-wider"
          >
            {Object.keys(COMPARISON_DB).map(k => <option key={k} value={k}>{k}</option>)}
          </select>
        </div>
        <div className="col-span-1 flex items-center justify-center p-4">
          <div className="w-16 h-16 rounded-full bg-blue-500/10 border border-blue-500/20 flex items-center justify-center text-blue-400 animate-pulse">
            <ICONS.Compare />
          </div>
        </div>
        <div className="col-span-1">
          <label className="block text-[10px] uppercase font-black text-orange-500 mb-4 tracking-widest text-right">Subject Beta</label>
          <select 
            value={topicB} 
            onChange={(e) => setTopicB(e.target.value)}
            className="w-full bg-void border border-orange-900/40 p-5 rounded-2xl text-white outline-none focus:border-yellow-500 transition shadow-inner text-right font-mystic tracking-wider"
          >
            {Object.keys(COMPARISON_DB).map(k => <option key={k} value={k}>{k}</option>)}
          </select>
        </div>
      </div>

      <div className="relative bg-black/40 rounded-[2.5rem] border border-white/5 overflow-hidden shadow-2xl backdrop-blur-sm">
        <table className="w-full text-left border-collapse">
          <thead>
            <tr className="bg-white/5">
              <th className="p-8 text-[11px] uppercase font-black text-gray-500 w-1/4 tracking-widest border-r border-white/5">Dimension</th>
              <th className="p-8 text-xl font-mystic text-blue-400 tracking-widest text-center border-r border-white/5">{topicA}</th>
              <th className="p-8 text-xl font-mystic text-orange-400 tracking-widest text-center">{topicB}</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-white/5">
            {metrics.map(attr => (
              <tr key={attr} className="group transition-colors">
                <td className="p-8 text-[11px] uppercase font-mono text-gray-400 font-bold bg-white/[0.01] border-r border-white/5">{attr}</td>
                
                {/* Cell for Topic A */}
                <td 
                  className="p-0 relative border-r border-white/5 group/cellA"
                  onMouseEnter={() => setHoveredCell({ topic: topicA, attr })}
                  onMouseLeave={() => setHoveredCell(null)}
                >
                  <div className="p-8 h-full flex flex-col justify-center cursor-help group-hover/cellA:bg-blue-500/5 transition-colors">
                    <div className="flex items-center gap-3">
                      <span className="text-[13px] text-gray-200 font-medium leading-relaxed">{dataA[attr].summary}</span>
                      <div className="w-1.5 h-1.5 rounded-full bg-blue-500/40 group-hover/cellA:bg-blue-400 transition-colors"></div>
                    </div>
                    {hoveredCell?.topic === topicA && hoveredCell.attr === attr && (
                      <div className="absolute top-1/2 left-[105%] -translate-y-1/2 w-80 z-[200] bg-black/95 backdrop-blur-2xl p-6 rounded-3xl border border-blue-500/30 shadow-[0_20px_60px_rgba(0,0,0,0.8)] animate-in fade-in zoom-in-95 duration-200 pointer-events-none">
                        <div className="text-[10px] text-blue-400 uppercase font-black tracking-widest mb-3 border-b border-white/5 pb-2">Technical Insight</div>
                        <p className="text-xs text-gray-300 leading-relaxed font-light">{dataA[attr].detail}</p>
                      </div>
                    )}
                  </div>
                </td>

                {/* Cell for Topic B */}
                <td 
                  className="p-0 relative group/cellB"
                  onMouseEnter={() => setHoveredCell({ topic: topicB, attr })}
                  onMouseLeave={() => setHoveredCell(null)}
                >
                  <div className="p-8 h-full flex flex-col justify-center cursor-help group-hover/cellB:bg-orange-500/5 transition-colors">
                    <div className="flex items-center gap-3">
                      <span className="text-[13px] text-gray-200 font-medium leading-relaxed">{dataB[attr].summary}</span>
                      <div className="w-1.5 h-1.5 rounded-full bg-orange-500/40 group-hover/cellB:bg-orange-400 transition-colors"></div>
                    </div>
                    {hoveredCell?.topic === topicB && hoveredCell.attr === attr && (
                      <div className="absolute top-1/2 right-[105%] -translate-y-1/2 w-80 z-[200] bg-black/95 backdrop-blur-2xl p-6 rounded-3xl border border-orange-500/30 shadow-[0_20px_60px_rgba(0,0,0,0.8)] animate-in fade-in zoom-in-95 duration-200 pointer-events-none">
                        <div className="text-[10px] text-orange-400 uppercase font-black tracking-widest mb-3 border-b border-white/5 pb-2">Technical Insight</div>
                        <p className="text-xs text-gray-300 leading-relaxed font-light">{dataB[attr].detail}</p>
                      </div>
                    )}
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <div className="mt-12 p-10 bg-gradient-to-br from-blue-900/10 to-transparent rounded-[2.5rem] border border-blue-800/20 relative overflow-hidden group min-h-[250px]">
        <div className="absolute top-0 right-0 p-8 opacity-10 group-hover:opacity-20 transition-opacity">
          <ICONS.Brain />
        </div>
        <h4 className="text-[11px] font-black text-blue-400 uppercase tracking-[0.3em] mb-4">Master's Synthesis</h4>
        <div className="relative z-10">
          <p className="italic text-base text-gray-300 leading-relaxed font-medium">
            "The interaction between <span className="text-blue-400 underline decoration-blue-500/30 underline-offset-4">{topicA}</span> and <span className="text-orange-400 underline decoration-orange-500/30 underline-offset-4">{topicB}</span> reveals the sacred architecture of your journey. One provides the structure of the classroom, while the other offers the keys to graduation. Sovereignty is found in the synthesis, not the separation."
          </p>
          <div className="mt-8 flex items-center gap-4 text-[10px] text-gray-500 uppercase font-black tracking-widest">
            <div className="w-8 h-px bg-gray-700"></div>
            SeTs Ryu Monastic Archives
          </div>
        </div>
      </div>
    </div>
  );
};

export default Comparator;
